"""Run this project end to end, and write down that it ran.

A repository whose continuous integration is frozen says nothing about itself: the green tick
is two years old, or absent. What replaces it is ``reports/run-evidence.json`` — the exact
command, the day, the revision, the tool versions, what it cost, and the tracked files it
produced. A reader can rerun that command and compare.

**The run must reproduce what the repository publishes.** The steps below regenerate the key
outputs; if any of them comes out different from the committed version, no evidence is
written and the differing files are named. That is the whole value of the exercise: evidence
that merely says « it ran » proves that something ran, not that what is published is what it
produces.

    uv run python scripts/smoke.py

Run it on a clean clone, before the release tag. No workflow writes this file: a committed
artefact regenerated by continuous integration is an artefact whose author is a machine
nobody watches.
"""

from __future__ import annotations

import json
import platform
import shutil
import subprocess
import sys
import time
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version

from mri_semisupervised.config import PROJECT_ROOT as ROOT_DIR

EVIDENCE = "reports/run-evidence.json"
COMMAND = "uv run python scripts/smoke.py"

#: The tracked files this run regenerates. Each one is compared with its committed version:
#: a smoke test that writes nothing proves that the process starts, not that it works.
#:
#: The experiments themselves are not here, and cannot be: they need the image archive and an
#: evening of GPU. What is reproduced is everything downstream of them — every published
#: figure and every run summary, from the per-fold metrics and the raw predictions the runs
#: left behind. A reader without the images can still check that the pictures and the pages
#: are what the committed numbers produce.
KEY_OUTPUT: tuple[str, ...] = (
    "reports/figures/arms_comparison.png",
    "reports/figures/calibration.png",
    "reports/figures/label_efficiency.png",
    "reports/figures/leak_price.png",
    "reports/figures/mechanisms.png",
    "reports/figures/paired_differences.png",
    "reports/figures/roc_arms.png",
    "reports/experiments/corrected/summary.md",
    "reports/experiments/legacy/summary.md",
)

#: The distributions whose version changes the result. Not the whole lock file: the reader
#: needs what would explain a different number, not an inventory.
TOOLS: tuple[str, ...] = ("torch", "torchvision", "scikit-learn", "matplotlib", "pandas")


def steps() -> None:
    """Redraw every figure and re-render every summary, from the artefacts the runs wrote.

    Nothing here catches: a step that failed would otherwise leave evidence saying the run
    succeeded.
    """
    for script in ("build_figures.py", "rebuild_summaries.py"):
        done = subprocess.run(
            [sys.executable, f"scripts/{script}"],
            cwd=ROOT_DIR,
            capture_output=True,
            text=True,
            check=False,
        )
        if done.returncode != 0:
            raise RuntimeError(
                f"scripts/{script} failed with code {done.returncode}: "
                f"{done.stdout.strip()[-800:]} {done.stderr.strip()[-800:]}"
            )
        print(f"  {script}")


# --- What the evidence records ----------------------------------------------


def _git(*arguments: str) -> str:
    done = subprocess.run(
        ["git", *arguments], cwd=ROOT_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def tool_versions() -> dict[str, str]:
    versions = {"python": platform.python_version()}
    for name in TOOLS:
        try:
            versions[name] = version(name)
        except PackageNotFoundError:
            versions[name] = "not installed"
    for binary, arguments in (("uv", ("--version",)), ("docker", ("--version",))):
        if shutil.which(binary):
            done = subprocess.run([binary, *arguments], capture_output=True, text=True, check=False)
            versions[binary] = done.stdout.strip() or "unknown"
    return versions


def reproduced() -> list[str]:
    """The key outputs the run did NOT reproduce: missing, untracked, or changed."""
    problems: list[str] = []
    for rel in KEY_OUTPUT:
        if not (ROOT_DIR / rel).exists():
            problems.append(f"{rel} — not produced")
            continue
        if not _git("ls-files", "--error-unmatch", rel):
            problems.append(f"{rel} — produced but not tracked by git")
            continue
        if _git("status", "--porcelain", "--", rel):
            problems.append(f"{rel} — differs from the committed version")
    return problems


def main() -> int:
    if not KEY_OUTPUT:
        print("scripts/smoke.py: name the tracked files this run regenerates", file=sys.stderr)
        return 1

    started = time.monotonic()
    steps()
    duration = round(time.monotonic() - started, 1)

    differences = reproduced()
    if differences:
        print("the run did not reproduce what is published:", file=sys.stderr)
        for line in differences:
            print(f"  {line}", file=sys.stderr)
        print(f"{EVIDENCE} not written", file=sys.stderr)
        return 1

    evidence = {
        "command": COMMAND,
        "ran_at": datetime.now(tz=UTC).date().isoformat(),
        "git_revision": _git("rev-parse", "HEAD"),
        "tool_versions": tool_versions(),
        "duration_seconds": duration,
        "key_output": list(KEY_OUTPUT),
        # Null, and said so: the workflows of this repository are frozen to a manual trigger,
        # so there is no run to point at. A missing key would read as an oversight.
        "workflow_run_url": None,
    }
    target = ROOT_DIR / EVIDENCE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"{EVIDENCE} written — {duration}s, {len(KEY_OUTPUT)} output(s) reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
